In [1]:
import numpy as np
list_= ['1','2','3','4','5']
array_list = np.array(object = list_)
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

##### Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

In [2]:
# Yes, python list is built-in data type whereus, for using numpy array we have to import numpy module.

# 1.Speed of execution of numpy array is faster than list.
# 2.Numpy array consume less memory as compared to python list , because list is hetrogenous in nature whereus numpy array is homogeneous in nature.
# 3.Numpy array is convenient to use.

print(type(list_))
print(type(array_list),array_list.dtype,sep="\n")



<class 'list'>
<class 'numpy.ndarray'>
<U1


##### Q2. Write a code to print the data type of each and every element of both the variables list_ and arra_list.

- Elements of list belongs to str data type, whereus element of array are unicode strings.

In [3]:
for i in list_:
    print(type(i),end=" ")

<class 'str'> <class 'str'> <class 'str'> <class 'str'> <class 'str'> 

In [4]:
for i in array_list:
    print(i.dtype,end=" ")

<U1 <U1 <U1 <U1 <U1 

##### Q3. Considering the following changes in the variable, array_list:

array_list = np.array(object = list_, dtype = int)

Will there be any difference in the data type of the elements present in both the variables, list_ and 
arra_list? If so then print the data types of each and every element present in both the variables, list_ 
and arra_list.


In [5]:
array_list=np.array(object=list_,dtype=int)

- Yes there will be now in numpy array with change the datatype into int. Elements of list belongs to str data type, whereus element of array are int.

In [6]:
for i in list_:
    print(type(i),end=" ")

<class 'str'> <class 'str'> <class 'str'> <class 'str'> <class 'str'> 

In [7]:
for i in array_list:
    print(i.dtype,end=" ")

int64 int64 int64 int64 int64 

In [8]:
#Consider the below code to answer further questions:

import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)

##### Q4. Write a code to find the following characteristics of variable, num_array:

(i)	 shape

(ii) size

In [9]:
print(num_array.shape)
print(num_array.size)

(2, 3)
6


##### Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.

[Hint: The size of the array will be 9 and the shape will be (3,3).]



In [10]:
import numpy as np
a=np.zeros((3,3),dtype=np.int8)
a

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int8)

##### Q6. Create an identity matrix of shape (5,5) using numpy functions?

[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [11]:
#using identity()
i=np.identity(5,dtype=np.int16)
i

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]], dtype=int16)

In [12]:
#using eye()
e=np.eye(5)
e

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])